Issues/new exception
eclipse-vertx/vertx-json-schema pull request #90
Opened 2023-02-21 16:25 UTC by pmlopes

Motivation:

Output unit is quite powerful as defined in the spec, however is doesn't feel natural in java. For this, we introduce a new method: `checkValidity()` that, like in other JDK places, will throw a typed exception with information about the location where the error happened and as stack trace the jumps the parser did until the error.

2023-02-21 16:29 UTC, pmlopes commented
@pk-work this introduces a new typed exception to avoid bugs of not catching runtime exceptions. Plus trying to retrofit to the old existing exception seems not to be possible.

If this works, we can merge it for 4.4 and update openapi for this change. If you believe that we should have a runtime exception, I'm also OK with it.

2023-02-22 07:29 UTC, pk-work requested changes

2023-02-22 07:29 UTC, pk-work commented on src/main/java/io/vertx/json/schema/OutputUnit.java
> +            }
In my opinion the "if" block is not necessary, simply pass last exception even if it is null. The constructor in the if block does the same.

2023-02-22 07:29 UTC, pk-work commented on src/main/java/io/vertx/json/schema/OutputUnit.java
> +              new StackTraceElement("[" + urlFormatter.apply(getInstanceLocation()) + "]", "<" + getKeyword() + ">", getKeywordLocation(), -1));
Please consider to create a method like
```
  private StackTraceElement toStackTraceElement(Function<String, String> urlFormatter) {
    return new StackTraceElement("[" + urlFormatter.apply(getInstanceLocation()) + "]", "<" + getKeyword() + ">", getKeywordLocation(), -1);
  }
```

to reduce redundancy.

2023-02-22 07:29 UTC, pk-work commented on src/main/java/io/vertx/json/schema/OutputUnit.java
> +  public void checkValidity() throws JsonSchemaValidationException {
I've tested `checkValidity` in vertx-openapi and it works as expected, but a test in vertx-json-schema to detect regressions could be beneficial.

2023-02-23 09:22 UTC, pk-work approved these changes

2023-02-23 14:44 UTC, merged